FirstProject/mysite/APP/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote$', views.vote, name='vote'),
]

FirstProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path(r'admin/', admin.site.urls),
    url(r'app/', include(('APP.urls', 'APP'),  namespace='APP')),
]

FirstProject/mysite/APP/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

FirstProject/mysite/APP/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Question


# Create your views here.
def index(request):
    latest_questions = Question.objects.order_by('-pub_date')[:50]
    context = {'latest_questions': latest_questions}
    return render(request, 'APP/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'APP/detail.html', {'question':question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'APP/results.html', {'question':question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk= request.POST['choice'])
    except:
        return render(request, 'APP/detail.html', {'question':question, 'error_message':'Please select a Choice'})
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('APP:results', args=(question.id,)))

FirstProject/mysite/APP/templates/APP/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Poll</title>
    <link rel="stylesheet" type = 'text/css' href="{%  static 'APP/bootstrap-4.3.1-dist/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type = 'text/css' href="{%  static 'APP/style.css' %}"/>
</head>
<body>
<hr>
<hr>
{%  include 'APP/header.html' %}
<div class="jumbotron">
        <h1>Simple Polls : </h1>

        {%  block main_content %}
        {% endblock %}
        </div>
{%  include 'APP/footer.html' %}
</body>
</html>

FirstProject/mysite/APP/templates/APP/detail.html
{% extends 'APP/base.html' %}
{% block main_content %}

<h1>{{question.question_text}}</h1>

{% if error_message %} <p><strong> {{error_message}} </strong></p> {% endif %}

<form action="{% url 'APP:vote' question.id %}" method="post">
    {% csrf_token %}
    {%  for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
    {% endfor %}
    <input type="submit" class = 'btn btn-success' value="Vote"/>


</form>

<a href="{% url 'APP:index' %}"> <-- Questions</a>


{% endblock %}

FirstProject/mysite/APP/templates/APP/footer.html
<footer class="footer">
        <p>    &copy; Since 2021, Inc.</p>
      </footer>

FirstProject/mysite/APP/templates/APP/header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="">Poll!</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#"></a>
          </li>
          <li class="nav-item dropdown">


          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

FirstProject/mysite/APP/templates/APP/index.html
{%  extends 'APP/base.html' %}
{%  block main_content %}

<h1>Choose a Question</h1>

{% if latest_questions %}
    <ul>
        {% for question in latest_questions %}
        <li><a href = {% url "APP:detail" question.id %}><b>{{question.question_text}}</b></a></li>
        {% endfor %}
    </ul>
{% else %}
    <p> You don't have any questions. </p>
{% endif %}

{% endblock %}

FirstProject/mysite/APP/templates/APP/results.html
{%  extends 'APP/base.html' %}
{%  block main_content %}

<h1>{{question.question_text}}</h1>

<ul>
    {%  for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} -- {{choice.votes}} vote{{ choice.votes|pluralize}}</li>
    {%  endfor %}
</ul>

<a href="{% url 'APP:detail' question.id %}"> Vote Again?</a>

{%  endblock %}